### PR TITLE
CI: Add retry script for Docker commands

### LINKED ISSUE #2489: loops in CircleCI
### Summary
I'm not sure if [for loops in config.yml](https://github.com/nipy/nipype/blob/master/.circleci/config.yml#L51) change anything, I think it does not retry if the command fails. I mostly noticed this when I tried to use the same logic in the Nipype Tutorial repo, where `datalad` command fails quite often. 

A simple example showing that CircleCI tries only once is [here](https://circleci.com/gh/djarecka/nipype_tutorial/64?utm_campaign=build-failed&utm_medium=email&utm_source=notification)

### PR DESCRIPTION
**Pull request by effigies**
Fixes #2489.

Changes proposed in this pull request
- Add `retry_cmd.sh` script
- Replace loops in `.circleci/config.yml`

### CODE REVIEW

**Comment by effigies** [comment]
There are some limits to this script WRT multi-command behavior.

```Python
$ retry_cmd.sh "echo TEST && exit 2"

File: tools/retry_cmd.sh [hunk 1]
```diff
@@ -0,0 +1,36 @@
+#!/bin/sh
+#
+# retry_cmd.sh [-n NLOOPS] [-s SLEEP] CMD
+#
+# Retry command until success or pre-specified number of failures
+#
+# 2018 Chris Markiewicz
+# Released into public domain
+
```
Comment (oesteban) [inline tools/retry_cmd.sh]: Doesn't this need to set `set +o pipefail` here to work? After some digging, I think the original problem reported in #2489 is just that the steps are run with `set -eo pipefile` (circle has started to run it with 2.0). Using both -eo will make the script to exit even with that `|| true` pipe.

Comment (effigies) [reply tools/retry_cmd.sh]: No, because those apply to each instance of the shell. It doesn't infect subprocesses.
